//===- Unpack.h - Recover the image a packed executable builds -*- C++ -*-===//
//
// NeverD Decompiler
//
//===----------------------------------------------------------------------===//
///
/// \file
/// Unpacking recovers the program a protected executable reconstructs in its
/// own address space. Recovery observes a bounded guest process and
/// rebuilds the image at the first transfer into code that did not exist when
/// the image was mapped. It neither guesses an entry point nor removes
/// virtualization; protected functions stay protected in the output.
///
/// Nothing here depends on one container, instruction set or guest system.
/// The input's container format selects how the file is validated and
/// rebuilt, its instruction set selects how a transfer is judged, and both
/// select the guest process profile that executes it. An RVA is an address
/// relative to the image base in every container.
///
//===----------------------------------------------------------------------===//
#ifndef NEVERD_UNPACK_UNPACK_H
#define NEVERD_UNPACK_UNPACK_H

#include "neverd/emulation/ProcessSession.h"

#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Error.h"

#include <cstdint>
#include <filesystem>
#include <optional>
#include <string>
#include <vector>

namespace neverd::unpack {
namespace defaults {
#define NEVERD_UNPACK_LIMIT(Name, Value) inline constexpr uint64_t Name = Value;
#include "neverd/unpack/Unpack.def"
#undef NEVERD_UNPACK_LIMIT
} // namespace defaults

enum class FormatKind {
#define NEVERD_UNPACK_FORMAT(Name, Text) Name,
#include "neverd/unpack/Unpack.def"
#undef NEVERD_UNPACK_FORMAT
};
enum class PackerKind {
#define NEVERD_UNPACK_PACKER(Name, Text) Name,
#include "neverd/unpack/Unpack.def"
#undef NEVERD_UNPACK_PACKER
};
enum class PackerEvidence {
#define NEVERD_UNPACK_EVIDENCE(Name, Text) Name,
#include "neverd/unpack/Unpack.def"
#undef NEVERD_UNPACK_EVIDENCE
};
enum class UnpackOutcome {
#define NEVERD_UNPACK_OUTCOME(Name, Text) Name,
#include "neverd/unpack/Unpack.def"
#undef NEVERD_UNPACK_OUTCOME
};
enum class EntrySource {
#define NEVERD_UNPACK_ENTRY_SOURCE(Name, Text) Name,
#include "neverd/unpack/Unpack.def"
#undef NEVERD_UNPACK_ENTRY_SOURCE
};
enum class ImportOrigin {
#define NEVERD_UNPACK_IMPORT_ORIGIN(Name, Text) Name,
#include "neverd/unpack/Unpack.def"
#undef NEVERD_UNPACK_IMPORT_ORIGIN
};
const char *formatKindName(FormatKind Kind);
const char *packerKindName(PackerKind Kind);
const char *packerEvidenceName(PackerEvidence Evidence);
const char *unpackOutcomeName(UnpackOutcome Outcome);
const char *importOriginName(ImportOrigin Origin);
const char *entrySourceName(EntrySource Source);

/// Compatibility vocabulary for consumers of earlier unpack reports.
/// Generic recovery does not identify protectors and leaves this empty.
struct PackerIdentification {
  PackerKind Kind = PackerKind::Unidentified;
  std::vector<PackerEvidence> Evidence;
};

/// Validate an image without executing it. An unsupported container or
/// malformed input returns Error. Valid images are Unidentified without
/// evidence; protector-specific identification is no longer performed.
llvm::Expected<PackerIdentification>
identifyPacker(llvm::ArrayRef<uint8_t> File);

/// Unpacking runs the input as a guest process, so it takes the same explicit
/// inputs. Only the resource defaults differ: a stub decompresses a whole
/// image before the program's first instruction.
struct UnpackOptions {
  /// Applies the unpacking defaults of Unpack.def, including those of each
  /// guest OS model.
  UnpackOptions();
  emulation::ProcessOptions Process;
  /// The one-based transfer into generated code to accept as the entry. Zero
  /// accepts the first transfer in the main program's entry invocation made
  /// on the stack that invocation started with,
  /// which is how a stub hands control to the program it carries. A protector
  /// that unpacks in stages, or that calls the program instead of jumping to
  /// it, needs the explicit position that a previous report lists.
  uint64_t Transfer = 0;
};

/// One transfer into code newer than the code that was running.
struct UnpackTransfer {
  uint64_t RVA;
  /// The stack pointer equals its initial value for the main program's entry
  /// invocation (or the first initializer before that invocation starts).
  bool StackBalanced;
  /// One for code generated from the loaded image, two for code generated by
  /// that code, and so on.
  uint64_t Generation;
  /// The OS model is executing the main program's entry invocation rather
  /// than an initialization or teardown callback it owns.
  bool ProgramInvocation = false;
};

/// One mapped extent of the rebuilt file: a section, or a segment in a
/// container that maps segments.
struct UnpackedSection {
  std::string Name;
  uint64_t RVA, VirtualSize, FileSize;
  /// Bytes that differ from the image as the guest loader mapped it.
  uint64_t GeneratedBytes;
};

struct UnpackedImport {
  std::string Module, Name;
  std::optional<uint16_t> Ordinal;
  /// The pointer-sized cell the program calls through.
  uint64_t SlotRVA;
  ImportOrigin Origin;
};

struct UnpackResult {
  FormatKind Format = FormatKind::PE64;
  PackerIdentification Packer;
  UnpackOutcome Outcome = UnpackOutcome::NoEntry;
  std::string Diagnostic;
  /// Stable guest architecture, profile, backend and process stop vocabulary
  /// from the guest process report.
  std::string Architecture, Profile;
  uint64_t ImageBase = 0;
  uint64_t PackedEntryRVA = 0;
  /// The first instruction of the recovered program and how it was
  /// established. Absent when no entry was accepted; never estimated.
  std::optional<uint64_t> EntryRVA;
  EntrySource Source = EntrySource::Transfer;
  /// Every transfer observed, in order, up to the one at which the image was
  /// rebuilt.
  std::vector<UnpackTransfer> Transfers;
  std::vector<UnpackedSection> Sections;
  std::vector<UnpackedImport> Imports;
  /// The rebuilt file, in the container of the input. Empty without an
  /// accepted entry.
  std::vector<uint8_t> Image;
  std::string Backend, BackendSelectionReason;
  std::string ProcessStop, ProcessDiagnostic;
  uint64_t PC = 0, Instructions = 0, Events = 0;
  /// Import repair discovers export calls and observes helper state in two
  /// additional bounded processes. Counts sum both runs; Stop describes the
  /// last run. These observations cover only the paths those processes reached.
  /// Setup failures and incomplete runs are visible independently of entry
  /// recovery; an unpacked outcome does not certify every protected import.
  struct ImportRepairReport {
    std::string Stop, Diagnostic;
    uint64_t ObservedCalls = 0, RepairedCalls = 0, ConflictingCalls = 0;
    uint64_t ObservedLoads = 0, RepairedLoads = 0;
    uint64_t Instructions = 0, Events = 0;
  } ImportRepair;
  /// TLS startup callbacks whose memory effects were captured. The rebuilt
  /// file bypasses their process-attach calls and forwards other TLS reasons.
  uint64_t MaterializedTLSCallbacks = 0;
};

/// Observe \p Input as a bounded guest process and rebuild its image at the
/// transfer accepted as its entry. Invalid input, options or an unavailable
/// backend return Error. A run that ends before such a transfer returns a
/// result whose outcome, transfers and process stop explain why.
llvm::Expected<UnpackResult> unpackFile(const std::filesystem::path &Input,
                                        const UnpackOptions &Options = {});

/// Strict options decoding. Every guest process option is accepted with its
/// usual meaning, plus "transfer". Unknown fields, null values, invalid
/// types and nonpositive limits are errors.
llvm::Expected<UnpackOptions> unpackOptionsFromJSON(llvm::StringRef Text);
/// The report omits the rebuilt bytes and records their size and digest.
std::string unpackResultJSON(const UnpackResult &Result,
                             llvm::StringRef OutputPath = {});
} // namespace neverd::unpack
#endif
