//===- ProcessObserver.h - Stopped guest process inspection -----*- C++ -*-===//
//
// NeverD Decompiler
//
//===----------------------------------------------------------------------===//
///
/// \file
/// Observation of a guest process at explicit execution boundaries. An
/// observer never executes guest code, never changes guest state and never
/// replenishes the workload budget; it only reads a stopped process and
/// selects where the next stop occurs.
///
//===----------------------------------------------------------------------===//
#ifndef NEVERD_EMULATION_PROCESSOBSERVER_H
#define NEVERD_EMULATION_PROCESSOBSERVER_H

#include "neverd/emulation/AddressSpace.h"
#include "neverd/emulation/ExecutionSession.h"
#include "neverd/emulation/ProcessSession.h"

#include <optional>
#include <string>
#include <vector>

namespace neverd::emulation {
/// One image known to the guest loader at the observed boundary.
struct ProcessModuleView {
  /// Guest basename as the loader records it.
  std::string Name;
  uint64_t Base, Size, Entry;
  /// The process image, as opposed to a dependency or system provider.
  bool Main;
  /// Bytes generated by the OS model rather than read from a guest file.
  bool Modeled;
};

/// One code address the guest loader can hand out for an export identity.
/// Several identities may share an address; each has its own record.
struct ProcessExportView {
  uint64_t Address;
  std::string Module, Name;
  std::optional<uint16_t> Ordinal;
};

/// The OS-owned stack allocation of the observed thread.
struct ProcessStackView {
  uint64_t Base, Size;
};

/// A stopped process. The view is valid only during the observer callback
/// that receives it and must not be retained.
class ProcessView {
public:
  virtual ~ProcessView();
  virtual GuestArchitecture architecture() const = 0;
  virtual llvm::Expected<RegisterValue> readRegister(CPURegister Register) = 0;
  /// Copy committed RAM independently of guest page permissions. Unmapped
  /// bytes and device mappings fail without a partial copy.
  virtual llvm::Error read(uint64_t Address,
                           llvm::MutableArrayRef<uint8_t> Bytes) = 0;
  /// Sorted layout coalesced by permissions and RAM/device kind.
  virtual llvm::Expected<std::vector<AddressMapping>> mappings() = 0;
  /// Resident images in loader registration order; the process image first.
  virtual std::vector<ProcessModuleView> modules() = 0;
  /// Every export identity currently bound to an OS-model entry address.
  virtual std::vector<ProcessExportView> exports() = 0;
  /// Execution belongs to the main program's entry invocation, including
  /// calls it makes. False for OS-owned initialization and teardown calls,
  /// or when the profile supplies no invocation provenance.
  virtual bool programInvocation() const { return false; }
  /// Main-image initializers whose OS-owned startup calls returned normally.
  /// These addresses are execution evidence, not predicted callback targets.
  virtual std::vector<uint64_t> completedInitializers() const { return {}; }
  /// The current thread's stack allocation, if the profile owns it.
  virtual std::optional<ProcessStackView> stack() const { return std::nullopt; }
  /// Number of OS service invocations so far, including calls still active.
  /// Missing provenance cannot establish that a helper has no OS effects.
  virtual std::optional<uint64_t> nativeCallCount() const {
    return std::nullopt;
  }
  /// Live main-image static TLS bytes of the current thread, excluding
  /// allocation padding. An empty vector means no data; std::nullopt means
  /// the profile supplies no TLS snapshot contract.
  virtual llvm::Expected<std::optional<std::vector<uint8_t>>>
  threadLocalMemory() {
    return std::nullopt;
  }
  /// The current instruction's decoded extent, using the CPU's fetch rules.
  /// Missing decoding support is an error, never a guessed instruction size.
  virtual llvm::Expected<uint32_t> instructionSize(uint64_t Address);
  /// No write or mapping change could have touched the RAM covered by the
  /// memory write watches installed for the preceding CPU run. False supplies
  /// no guarantee. Newly watched ranges still require an initial snapshot.
  virtual bool watchedMemoryUnchanged() const { return false; }
};

/// Receives a process at its start and at each execution watch.
class ProcessObserver {
public:
  virtual ~ProcessObserver();
  /// Images are mapped and linked and the initial thread exists; no guest
  /// instruction has executed. Returns the initial execution watches.
  virtual llvm::Expected<std::vector<ExecutionWatch>>
  started(ProcessView &Process) = 0;
  /// The process is suspended before the first instruction of a watched range
  /// at \p PC. Returning a watch set resumes with it; the reported instruction
  /// executes once without matching again. Returning std::nullopt ends the
  /// run with ProcessStopReason::Observer.
  virtual llvm::Expected<std::optional<std::vector<ExecutionWatch>>>
  watched(ProcessView &Process, uint64_t PC) = 0;
  /// The OS model has prepared a guest invocation or restored a suspended
  /// caller. The initial invocation is covered by started(). Returning a
  /// watch set replaces the current watches; std::nullopt keeps them.
  virtual llvm::Expected<std::optional<std::vector<ExecutionWatch>>>
  invoking(ProcessView &Process);
  /// The OS has identified an export gate, before API effects or an
  /// unsupported-export stop. Identity does not imply a modeled signature.
  /// ReturnAddress is absent when the ABI return location could not be read.
  virtual llvm::Error exporting(ProcessView &Process,
                                const ProcessExportView &Export,
                                std::optional<uint64_t> ReturnAddress);
  /// The model is about to resume the CPU. This includes changes made by OS
  /// services while stopped and committed guest writes that yielded the CPU.
  /// A returned set replaces execution watches; std::nullopt keeps them.
  virtual llvm::Expected<std::optional<std::vector<ExecutionWatch>>>
  resuming(ProcessView &Process);
  /// RAM ranges to invalidate after a guest write, through any physical alias.
  /// The model replaces these watches before each CPU resume.
  virtual std::vector<MemoryWriteWatch> writeWatches() const { return {}; }
};

/// As emulateProcess, under observation. Profiles without an observation
/// contract fail before execution rather than ignoring the observer.
llvm::Expected<ProcessResult> observeProcess(const std::filesystem::path &Path,
                                             ProcessProfile Profile,
                                             const ProcessOptions &Options,
                                             ProcessObserver &Observer);
} // namespace neverd::emulation
#endif
