#ifndef NEVERD_LIBC_LIBCPTHREAD_H
#define NEVERD_LIBC_LIBCPTHREAD_H

#include "neverd/libc/LibCNames.h"

#include <array>
#include <string_view>

namespace neverd::libc {

/// POSIX pthread.h — threads, mutexes, conditions, rwlocks, barriers, TLS
inline constexpr std::string_view kPthreadHeader = "pthread.h";

inline constexpr std::array kPthreadFunctions = {
    // lifecycle
    "pthread_create",
    "pthread_detach",
    "pthread_equal",
    "pthread_exit",
    "pthread_join",
    "pthread_self",
    "pthread_atfork",
    // attributes
    "pthread_attr_destroy",
    "pthread_attr_getdetachstate",
    "pthread_attr_getguardsize",
    "pthread_attr_getschedparam",
    "pthread_attr_getstack",
    "pthread_attr_getstacksize",
    "pthread_attr_init",
    "pthread_attr_setdetachstate",
    "pthread_attr_setguardsize",
    "pthread_attr_setschedparam",
    "pthread_attr_setstack",
    "pthread_attr_setstacksize",
    // mutex
    "pthread_mutex_destroy",
    "pthread_mutex_init",
    "pthread_mutex_lock",
    "pthread_mutex_trylock",
    "pthread_mutex_unlock",
    "pthread_mutexattr_destroy",
    "pthread_mutexattr_getpshared",
    "pthread_mutexattr_getrobust",
    "pthread_mutexattr_gettype",
    "pthread_mutexattr_init",
    "pthread_mutexattr_setpshared",
    "pthread_mutexattr_setrobust",
    "pthread_mutexattr_settype",
    // condition variable
    "pthread_cond_broadcast",
    "pthread_cond_destroy",
    "pthread_cond_init",
    "pthread_cond_signal",
    "pthread_cond_timedwait",
    "pthread_cond_wait",
    "pthread_condattr_destroy",
    "pthread_condattr_getclock",
    "pthread_condattr_getpshared",
    "pthread_condattr_init",
    "pthread_condattr_setclock",
    "pthread_condattr_setpshared",
    // read-write lock
    "pthread_rwlock_destroy",
    "pthread_rwlock_init",
    "pthread_rwlock_rdlock",
    "pthread_rwlock_timedrdlock",
    "pthread_rwlock_timedwrlock",
    "pthread_rwlock_tryrdlock",
    "pthread_rwlock_trywrlock",
    "pthread_rwlock_unlock",
    "pthread_rwlock_wrlock",
    "pthread_rwlockattr_destroy",
    "pthread_rwlockattr_getpshared",
    "pthread_rwlockattr_init",
    "pthread_rwlockattr_setpshared",
    // barrier
    "pthread_barrier_destroy",
    "pthread_barrier_init",
    "pthread_barrier_wait",
    // once
    "pthread_once",
    // thread-specific data
    "pthread_getspecific",
    "pthread_key_create",
    "pthread_key_delete",
    "pthread_setspecific",
    // spinlock
    "pthread_spin_destroy",
    "pthread_spin_init",
    "pthread_spin_lock",
    "pthread_spin_trylock",
    "pthread_spin_unlock",
    // GNU extensions commonly seen in binaries
    "pthread_getattr_np",
    "pthread_getname_np",
    "pthread_setname_np",
};

/// Fixed arity of the pthread.h functions.  {IntArgs, FpArgs}.
inline constexpr auto kPthreadArity = std::to_array<LibCArityEntry>({
    {"pthread_create", {4, 0}},
    {"pthread_detach", {1, 0}},
    {"pthread_equal", {2, 0}},
    {"pthread_exit", {1, 0}},
    {"pthread_join", {2, 0}},
    {"pthread_self", {0, 0}},
    {"pthread_atfork", {3, 0}},
    {"pthread_attr_destroy", {1, 0}},
    {"pthread_attr_getdetachstate", {2, 0}},
    {"pthread_attr_getguardsize", {2, 0}},
    {"pthread_attr_getschedparam", {2, 0}},
    {"pthread_attr_getstack", {3, 0}},
    {"pthread_attr_getstacksize", {2, 0}},
    {"pthread_attr_init", {1, 0}},
    {"pthread_attr_setdetachstate", {2, 0}},
    {"pthread_attr_setguardsize", {2, 0}},
    {"pthread_attr_setschedparam", {2, 0}},
    {"pthread_attr_setstack", {3, 0}},
    {"pthread_attr_setstacksize", {2, 0}},
    {"pthread_mutex_destroy", {1, 0}},
    {"pthread_mutex_init", {2, 0}},
    {"pthread_mutex_lock", {1, 0}},
    {"pthread_mutex_trylock", {1, 0}},
    {"pthread_mutex_unlock", {1, 0}},
    {"pthread_mutexattr_destroy", {1, 0}},
    {"pthread_mutexattr_getpshared", {2, 0}},
    {"pthread_mutexattr_getrobust", {2, 0}},
    {"pthread_mutexattr_gettype", {2, 0}},
    {"pthread_mutexattr_init", {1, 0}},
    {"pthread_mutexattr_setpshared", {2, 0}},
    {"pthread_mutexattr_setrobust", {2, 0}},
    {"pthread_mutexattr_settype", {2, 0}},
    {"pthread_cond_broadcast", {1, 0}},
    {"pthread_cond_destroy", {1, 0}},
    {"pthread_cond_init", {2, 0}},
    {"pthread_cond_signal", {1, 0}},
    {"pthread_cond_timedwait", {3, 0}},
    {"pthread_cond_wait", {2, 0}},
    {"pthread_condattr_destroy", {1, 0}},
    {"pthread_condattr_getclock", {2, 0}},
    {"pthread_condattr_getpshared", {2, 0}},
    {"pthread_condattr_init", {1, 0}},
    {"pthread_condattr_setclock", {2, 0}},
    {"pthread_condattr_setpshared", {2, 0}},
    {"pthread_rwlock_destroy", {1, 0}},
    {"pthread_rwlock_init", {2, 0}},
    {"pthread_rwlock_rdlock", {1, 0}},
    {"pthread_rwlock_timedrdlock", {2, 0}},
    {"pthread_rwlock_timedwrlock", {2, 0}},
    {"pthread_rwlock_tryrdlock", {1, 0}},
    {"pthread_rwlock_trywrlock", {1, 0}},
    {"pthread_rwlock_unlock", {1, 0}},
    {"pthread_rwlock_wrlock", {1, 0}},
    {"pthread_rwlockattr_destroy", {1, 0}},
    {"pthread_rwlockattr_getpshared", {2, 0}},
    {"pthread_rwlockattr_init", {1, 0}},
    {"pthread_rwlockattr_setpshared", {2, 0}},
    {"pthread_barrier_destroy", {1, 0}},
    {"pthread_barrier_init", {3, 0}},
    {"pthread_barrier_wait", {1, 0}},
    {"pthread_once", {2, 0}},
    {"pthread_getspecific", {1, 0}},
    {"pthread_key_create", {2, 0}},
    {"pthread_key_delete", {1, 0}},
    {"pthread_setspecific", {2, 0}},
    {"pthread_spin_destroy", {1, 0}},
    {"pthread_spin_init", {2, 0}},
    {"pthread_spin_lock", {1, 0}},
    {"pthread_spin_trylock", {1, 0}},
    {"pthread_spin_unlock", {1, 0}},
    {"pthread_getattr_np", {2, 0}},
    {"pthread_getname_np", {3, 0}},
    {"pthread_setname_np", {2, 0}},
});

} // namespace neverd::libc

#endif // NEVERD_LIBC_LIBCPTHREAD_H
