#ifndef NEVERD_LIBC_LIBCSTDIO_H
#define NEVERD_LIBC_LIBCSTDIO_H

#include "neverd/libc/LibCNames.h"

#include <array>
#include <string_view>

namespace neverd::libc {

/// ISO C stdio.h — formatted I/O, streams, file operations
inline constexpr std::string_view kStdioHeader = "stdio.h";

inline constexpr std::array kStdioFunctions = {
    "__overflow",
    "__uflow",
    "asprintf",
    "clearerr",
    "clearerr_unlocked",
    "ctermid",
    "dprintf",
    "fclose",
    "fdopen",
    "feof",
    "feof_unlocked",
    "ferror",
    "ferror_unlocked",
    "fflush",
    "fflush_unlocked",
    "fgetc",
    "fgetc_unlocked",
    "fgetpos",
    "fgets",
    "fileno",
    "flockfile",
    "fmemopen",
    "fopen",
    "fopencookie",
    "fprintf",
    "fputc",
    "fputc_unlocked",
    "fputs",
    "fputs_unlocked",
    "fread",
    "fread_unlocked",
    "freopen",
    "fscanf",
    "fseek",
    "fseeko",
    "fsetpos",
    "ftell",
    "ftello",
    "ftrylockfile",
    "funlockfile",
    "fwrite",
    "fwrite_unlocked",
    "getc",
    "getc_unlocked",
    "getchar",
    "getchar_unlocked",
    "getdelim",
    "getline",
    "gets",
    "getw",
    "open_memstream",
    "pclose",
    "perror",
    "popen",
    "printf",
    "putc",
    "putchar",
    "puts",
    "putw",
    "remove",
    "rename",
    "renameat",
    "rewind",
    "scanf",
    "setbuf",
    "setbuffer",
    "setlinebuf",
    "setvbuf",
    "snprintf",
    "sprintf",
    "sscanf",
    "tempnam",
    "tmpfile",
    "tmpnam",
    "ungetc",
    "vasprintf",
    "vdprintf",
    "vfprintf",
    "vfscanf",
    "vprintf",
    "vscanf",
    "vsnprintf",
    "vsprintf",
    "vsscanf",
};

/// Fixed arity of the non-variadic stdio.h functions.  {IntArgs, FpArgs}.
inline constexpr auto kStdioArity = std::to_array<LibCArityEntry>({
    {"puts", {1, 0}},
    {"fputs", {2, 0}},
    {"fputc", {2, 0}},
    {"putc", {2, 0}},
    {"putchar", {1, 0}},
    {"fgetc", {1, 0}},
    {"getc", {1, 0}},
    {"getchar", {0, 0}},
    {"fgets", {3, 0}},
    {"fopen", {2, 0}},
    {"freopen", {3, 0}},
    {"fdopen", {2, 0}},
    {"fclose", {1, 0}},
    {"fflush", {1, 0}},
    {"fread", {4, 0}},
    {"fwrite", {4, 0}},
    {"fseek", {3, 0}},
    {"fseeko", {3, 0}},
    {"ftell", {1, 0}},
    {"ftello", {1, 0}},
    {"rewind", {1, 0}},
    {"fgetpos", {2, 0}},
    {"fsetpos", {2, 0}},
    {"feof", {1, 0}},
    {"ferror", {1, 0}},
    {"clearerr", {1, 0}},
    {"fileno", {1, 0}},
    {"remove", {1, 0}},
    {"rename", {2, 0}},
    {"perror", {1, 0}},
    {"setbuf", {2, 0}},
    {"setvbuf", {4, 0}},
    {"ungetc", {2, 0}},
    {"tmpfile", {0, 0}},
    {"popen", {2, 0}},
    {"pclose", {1, 0}},
    {"putw", {2, 0}},
    {"getw", {1, 0}},
    {"vdprintf", {3, 0}},
    {"vfprintf", {3, 0}},
    {"vfscanf", {3, 0}},
    {"vprintf", {2, 0}},
    {"vscanf", {2, 0}},
    {"vsnprintf", {4, 0}},
    {"vsprintf", {3, 0}},
    {"vsscanf", {3, 0}},
    {"clearerr_unlocked", {1, 0}},
    {"ctermid", {1, 0}},
    {"feof_unlocked", {1, 0}},
    {"ferror_unlocked", {1, 0}},
    {"fgetc_unlocked", {1, 0}},
    {"flockfile", {1, 0}},
    {"fmemopen", {3, 0}},
    {"fopencookie", {3, 0}},
    {"fread_unlocked", {4, 0}},
    {"ftrylockfile", {1, 0}},
    {"funlockfile", {1, 0}},
    {"fwrite_unlocked", {4, 0}},
    {"getc_unlocked", {1, 0}},
    {"getchar_unlocked", {0, 0}},
    {"getdelim", {4, 0}},
    {"getline", {3, 0}},
    {"open_memstream", {2, 0}},
    {"setbuffer", {3, 0}},
    {"setlinebuf", {1, 0}},
    {"tempnam", {2, 0}},
    {"tmpnam", {1, 0}},
    {"vasprintf", {3, 0}},
    {"fflush_unlocked", {1, 0}},
    {"fputc_unlocked", {2, 0}},
    {"fputs_unlocked", {2, 0}},
    {"renameat", {4, 0}},
    {"overflow", {2, 0}},
    {"uflow", {1, 0}},
});

} // namespace neverd::libc

#endif // NEVERD_LIBC_LIBCSTDIO_H
