#!/usr/bin/env python3
"""Extract compiler-declared NSString format contracts for variadic messages.

Only declarations common to all corresponding macOS/iOS profiles are emitted.
Every alternative declaration participates, including fixed, unannotated and
conflicting declarations. The ordinary declaration catalog keeps rejecting
these selectors until a call proves its actual format and argument types.
"""
import argparse
import ctypes
import json
from pathlib import Path
import re
import tempfile

try:
    from .generate_objc_declarations import Clang, CXCursor, CXString, TARGETS, catalog_rows
except ImportError:
    from generate_objc_declarations import Clang, CXCursor, CXString, TARGETS, catalog_rows


def format_contract(pretty, hidden_parameters=2):
    # Attribute string payloads are not declarations (for example annotate).
    pretty = re.sub(r'"(?:\\.|[^"\\])*"', '\"\"', pretty)
    contracts = re.findall(
        r'__attribute__\(\(format\(NSString,\s*(\d+),\s*(\d+)\)\)\)', pretty)
    if len(contracts) != 1:
        return None
    parameter, first_variadic = map(int, contracts[0])
    if not 1 <= parameter < first_variadic <= 63:
        return None
    # Attribute positions count explicit arguments from one. The machine
    # signature may carry hidden parameters before those arguments.
    return parameter - 1 + hidden_parameters, first_variadic - 1 + hidden_parameters


class FormatDeclarations(Clang):
    hidden_parameters = 2

    def __init__(self, library):
        super().__init__(library)
        self.bind('clang_Cursor_getNumArguments', ctypes.c_int, CXCursor)
        self.bind('clang_getCursorPrintingPolicy', ctypes.c_void_p, CXCursor)
        self.bind('clang_PrintingPolicy_dispose', None, ctypes.c_void_p)
        self.bind('clang_getCursorPrettyPrinted', CXString, CXCursor, ctypes.c_void_p)

    def declaration(self, cursor):
        ordinary = super().declaration(cursor)
        if ordinary is None:
            return None
        selector, _ = ordinary
        if not self.clang_Cursor_isVariadic(cursor):
            return selector, ''
        policy = self.clang_getCursorPrintingPolicy(cursor)
        try:
            # Print the parsed AST, with expanded attributes. No header macro
            # text is interpreted as a compiler-validated format contract.
            pretty = self.string(self.clang_getCursorPrettyPrinted(cursor, policy))
        finally:
            self.clang_PrintingPolicy_dispose(policy)
        contract = format_contract(pretty, self.hidden_parameters)
        encoding = self.string(self.clang_getDeclObjCTypeEncoding(cursor))
        if not contract or not encoding or contract[1] != self.clang_Cursor_getNumArguments(cursor) + self.hidden_parameters:
            return selector, ''
        return selector, json.dumps([encoding, *contract], separators=(',', ':'))


def format_rows(profiles):
    for selector, arm, intel in catalog_rows(profiles):
        if not arm or not intel:
            continue
        a, b = json.loads(arm), json.loads(intel)
        if a[1:] != b[1:]:
            continue
        yield selector, a[0], b[0], *a[1:]


def render(profiles, version, compiler):
    lines = ['// clang-format off',
             '// Generated by scripts/generate_objc_format_declarations.py.',
             f'// Compiler-derived Foundation format contracts: MacOSX SDK {version}.',
             f'// {compiler}', '// Target profiles: ' + ', '.join(TARGETS),
             '// No framework implementation is included.']
    for row in format_rows(profiles):
        lines.append('{' + ', '.join(map(json.dumps, row)) + '},')
    lines.append('// clang-format on')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sdk', type=Path, required=True)
    parser.add_argument('--libclang', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    sdk = args.sdk.resolve(strict=True)
    clang = FormatDeclarations(args.libclang)
    with tempfile.TemporaryDirectory(prefix='neverd-format-declarations-') as work:
        source = Path(work) / 'declarations.m'
        source.write_text('#import <Foundation/Foundation.h>\n')
        profiles = [clang.extract(source, sdk, target) for target in TARGETS]
    version = json.loads((sdk/'SDKSettings.json').read_text())['Version']
    output = render(profiles, version, clang.string(clang.clang_getClangVersion()))
    if args.check:
        if args.output.read_text() != output:
            parser.error('generated catalog differs; regenerate with this SDK')
    else:
        args.output.write_text(output)
    print(f'verified {sum(line.startswith(chr(123)) for line in output.splitlines())} format contracts')


if __name__ == '__main__':
    main()
