#!/usr/bin/env python3
"""Turn richprint's comp_id.txt into the table NeverD reads Rich headers with.

Microsoft's linker records, between a PE file's DOS stub and its PE header,
which build of which tool produced every object it linked (the "Rich header").
richprint's comp_id.txt maps each of those @comp.id values to the tool and the
Visual Studio release it belongs to.  Two kinds of record are kept:

  * a product record (four hex digits) names the kind of tool a product id is,
    for every build of it;
  * a build record (eight hex digits, product id and build) names the Visual
    Studio release that build shipped in.

The generated table keeps the tool kind, the Visual Studio year and richprint's
description of every record.  Nothing is inferred beyond what the file states.
"""

import argparse
import hashlib
import json
import re
from pathlib import Path

REVISION = "49f2dc93504db4a669c968fa80eb9b34591cb557"
SOURCE = "https://github.com/dishather/richprint/blob/" + REVISION + "/comp_id.txt"
SOURCE_SHA256 = "f5f196791faf8d6e90b90b720b362707ff460df592330299f3610e81dd059907"

# richprint's marks, from the legend at the top of comp_id.txt.  The "Std" and
# "Book" editions of the old compilers produce code like the others.
TOOLS = {
    "[ C ]": "C", "[C S]": "C", "[C B]": "C",
    "[C++]": "Cpp", "[CPP]": "Cpp", "[C+S]": "Cpp", "[C+B]": "Cpp",
    "[ASM]": "Asm", "[LNK]": "Linker", "[RES]": "Resource",
    "[IMP]": "Import", "[EXP]": "Export",
    "[LTC]": "LtcgC", "[LT+]": "LtcgCpp", "[LTM]": "LtcgMsil",
    "[PGO]": "PogoInstrumentC", "[PG+]": "PogoInstrumentCpp",
    "[POC]": "PogoOptimizeC", "[PO+]": "PogoOptimizeCpp",
    "[CIL]": "CvtcilC", "[CI+]": "CvtcilCpp",
    "[OMF]": "Cvtomf", "[PGD]": "Cvtpgd", "[AOb]": "AliasObj",
    "[BSC]": "Basic", "[ILA]": "IlAsm", "[---]": "Unmarked",
}

_RECORD = re.compile(r"^(?P<id>[0-9A-Fa-f]{4}|[0-9A-Fa-f]{8})\s+(?P<tag>\[[^]]{3}\])\s+(?P<text>.*)$")


def release_year(description):
    """The Visual Studio year a description names, or 0.

    VS97 and VS98 are the 5.0 and 6.0 releases; later ones carry their year,
    and "VS2015+" names the release its product ids first shipped in.
    """

    match = re.match(r"VS(\d{4})|VS(97|98|6)\b", description)
    if not match:
        return 0
    if match.group(1):
        return int(match.group(1))
    return {"97": 1997, "98": 1998, "6": 1998}[match.group(2)]


def records(text):
    """Product records and build records, as (id, tool, year, interpolated, text)."""

    products, builds, seen = {}, {}, set()
    for number, raw in enumerate(text.splitlines(), 1):
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        match = _RECORD.match(line)
        if not match:
            raise ValueError(f"line {number}: not a comp.id record: {raw!r}")
        tag = match.group("tag")
        if tag not in TOOLS:
            raise ValueError(f"line {number}: unknown mark {tag}")
        value = int(match.group("id"), 16)
        key = (len(match.group("id")), value)
        if key in seen:
            raise ValueError(f"line {number}: duplicate comp.id {match.group('id')}")
        seen.add(key)
        description = match.group("text").strip()
        interpolated = description.endswith("(*)")
        if interpolated:
            description = description[:-3].rstrip()
        entry = (TOOLS[tag], release_year(description), interpolated, description)
        if len(match.group("id")) == 4:
            products[value] = entry
        else:
            builds[(value >> 16, value & 0xFFFF)] = entry
    return products, builds


def render(products, builds, digest):
    lines = [
        "// clang-format off",
        "// Generated by scripts/generate_rich_comp_ids.py.",
        "// @comp.id records from richprint's comp_id.txt:",
        "// " + SOURCE,
        "// SHA256: " + digest,
        "// Copyright (c) 2015-2024 dishather (https://github.com/dishather).",
        "// BSD-2-Clause; see LICENSES/richprint.txt.",
        "// Changes: keep each record's tool kind, Visual Studio year and",
        "// description, sorted by product id and build, 2026-09-28.",
        "static constexpr RichProductRecord RichProducts[] = {",
    ]
    for prod_id, (tool, year, _, text) in sorted(products.items()):
        lines.append(f"    {{0x{prod_id:04x}, RichTool::{tool}, {year}, {json.dumps(text)}}},")
    lines += ["};", "static constexpr RichBuildRecord RichBuilds[] = {"]
    for (prod_id, build), (tool, year, interpolated, text) in sorted(builds.items()):
        lines.append(
            f"    {{0x{prod_id:04x}, {build}, RichTool::{tool}, {year}, "
            f"{str(interpolated).lower()}, {json.dumps(text)}}},"
        )
    return "\n".join(lines + ["};", "// clang-format on", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--input", required=True, type=Path,
                        help="comp_id.txt at the pinned richprint revision")
    parser.add_argument("--source-sha256", required=True)
    parser.add_argument("--output", type=Path,
                        default=Path("lib/loader/COFF/RichCompIds.inc"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = args.input.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if args.source_sha256 != SOURCE_SHA256 or digest != SOURCE_SHA256:
        parser.error("comp_id.txt does not match the pinned revision's hash")
    products, builds = records(data.decode("utf-8"))
    if not products or not builds:
        parser.error("comp_id.txt supplies no records")
    output = render(products, builds, digest)
    if args.check:
        if not args.output.exists() or args.output.read_text() != output:
            parser.error("generated Rich header table differs")
    else:
        args.output.write_text(output)
    print(f"{len(products)} product records, {len(builds)} build records")


if __name__ == "__main__":
    main()
