#!/usr/bin/env python3
"""Verify documented predicate-format entry points against SDK declarations.

The predicate language has no NSString format attribute. Its public contract
is documented in Apple's Predicate Programming Guide, Creating Predicates and
Predicate Format String Syntax. Compiler-observed owners, signatures and all
alternative declarations must still agree across the four Darwin profiles.
No framework implementation is included.
"""
import argparse
import ctypes
import json
from pathlib import Path
import tempfile

try:
    from .generate_objc_declarations import CXCursor, CXString, PrintingClang, TARGETS
    from .generate_objc_format_declarations import format_rows
    from .generate_darwin_declarations import CXType
except ImportError:
    from generate_objc_declarations import CXCursor, CXString, PrintingClang, TARGETS
    from generate_objc_format_declarations import format_rows
    from generate_darwin_declarations import CXType


def predicate_contract(owner, selector, class_method, variadic, parameters, result):
    entry_points = {('NSPredicate', 'predicateWithFormat:'),
                    ('NSExpression', 'expressionWithFormat:')}
    if ((owner, selector) not in entry_points or not class_method or not variadic
            or [''.join(t.split()) for t in parameters] != ['NSString*']
            or ''.join(result.split()) != owner + '*'):
        return None
    return 2, 3


class PredicateDeclarations(PrintingClang):
    def __init__(self, library):
        super().__init__(library)
        self.bind('clang_getCursorSemanticParent', CXCursor, CXCursor)
        self.bind('clang_Cursor_getArgument', CXCursor, CXCursor, ctypes.c_uint)
        self.bind('clang_getCursorType', CXType, CXCursor)
        self.bind('clang_getCursorResultType', CXType, CXCursor)
        self.bind('clang_getTypeSpelling', CXString, CXType)

    def declaration(self, cursor):
        ordinary = super().declaration(cursor)
        if ordinary is None:
            return None
        selector, _ = ordinary
        parent = self.clang_getCursorSemanticParent(cursor)
        if parent.kind != 11:  # An actual Objective-C interface declaration.
            return selector, ''
        count = self.clang_Cursor_getNumArguments(cursor)
        if count != 1:
            return selector, ''
        argument = self.clang_Cursor_getArgument(cursor, 0)
        contract = predicate_contract(
            self.string(self.clang_getCursorSpelling(parent)), selector,
            cursor.kind == 17, bool(self.clang_Cursor_isVariadic(cursor)),
            [self.string(self.clang_getTypeSpelling(self.clang_getCursorType(argument)))],
            self.string(self.clang_getTypeSpelling(self.clang_getCursorResultType(cursor))))
        encoding = self.string(self.clang_getDeclObjCTypeEncoding(cursor))
        if not contract or not encoding:
            return selector, ''
        return selector, json.dumps([encoding, *contract], separators=(',', ':'))


def render(profiles, version, compiler):
    lines = ['// clang-format off',
             '// Generated by scripts/generate_objc_predicate_declarations.py.',
             f'// Compiler-verified predicate entry points: MacOSX SDK {version}.',
             f'// {compiler}', '// Target profiles: ' + ', '.join(TARGETS),
             '// No framework implementation is included.']
    for row in format_rows(profiles):
        lines.append('{' + ', '.join(map(json.dumps, row)) +
                     ', SourceCallTypeHint::FormatSyntax::Predicate},')
    lines.append('// clang-format on')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sdk', type=Path, required=True)
    parser.add_argument('--libclang', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    sdk = args.sdk.resolve(strict=True)
    clang = PredicateDeclarations(args.libclang)
    with tempfile.TemporaryDirectory(prefix='neverd-predicate-declarations-') as work:
        source = Path(work) / 'declarations.m'
        source.write_text('#import <Foundation/Foundation.h>\n')
        profiles = [clang.extract(source, sdk, target) for target in TARGETS]
    version = json.loads((sdk / 'SDKSettings.json').read_text())['Version']
    output = render(profiles, version, clang.string(clang.clang_getClangVersion()))
    if args.check:
        if args.output.read_text() != output:
            parser.error('generated catalog differs; regenerate with this SDK')
    else:
        args.output.write_text(output)
    print(f'verified {sum(line.startswith(chr(123)) for line in output.splitlines())} predicate contracts')


if __name__ == '__main__':
    main()
