#!/usr/bin/env python3
"""Extract common Darwin C NSString-format declarations and exact exports."""
import argparse
import json
from pathlib import Path
import tempfile

try:
    from .generate_darwin_declarations import CDeclarations, load_exports
    from .generate_objc_format_declarations import FormatDeclarations, format_rows
    from .generate_objc_declarations import TARGETS
except ImportError:
    from generate_darwin_declarations import CDeclarations, load_exports
    from generate_objc_format_declarations import FormatDeclarations, format_rows
    from generate_objc_declarations import TARGETS


class CFormatDeclarations(FormatDeclarations, CDeclarations):
    hidden_parameters = 0

    def declaration(self, cursor):
        result = super().declaration(cursor)
        if result is None:
            return None
        function = self.clang_getCursorType(cursor)
        if (function.kind != 111 or
                self.clang_getFunctionTypeCallingConv(function) != 1 or
                self.clang_Cursor_isFunctionInlined(cursor)):
            return result[0], ''
        return result


def render(profiles, exports, version, compiler):
    lines = ['// clang-format off',
             '// Generated by scripts/generate_darwin_format_declarations.py.',
             f'// Compiler-derived C format and export facts: MacOSX SDK {version}.',
             f'// {compiler}', '// Target profiles: ' + ', '.join(TARGETS),
             '// No SDK implementation is included.']
    for row in format_rows(profiles):
        modules = ['|'.join(sorted(index.get(row[0], ()))) for index in exports]
        if not all(modules):
            continue
        lines.append('{' + ', '.join(map(json.dumps, [*row, *modules])) + '},')
    lines.append('// clang-format on')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sdk', type=Path, required=True)
    parser.add_argument('--libclang', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    sdk = args.sdk.resolve(strict=True)
    clang = CFormatDeclarations(args.libclang)
    with tempfile.TemporaryDirectory(prefix='neverd-c-format-declarations-') as work:
        source = Path(work) / 'declarations.m'
        source.write_text('#import <Foundation/Foundation.h>\n')
        profiles = [clang.extract(source, sdk, target) for target in TARGETS]
    version = json.loads((sdk/'SDKSettings.json').read_text())['Version']
    output = render(profiles, load_exports(sdk), version,
                    clang.string(clang.clang_getClangVersion()))
    if args.check:
        if args.output.read_text() != output:
            parser.error('generated catalog differs; regenerate with this SDK')
    else:
        args.output.write_text(output)
    print(f'verified {sum(line.startswith(chr(123)) for line in output.splitlines())} C format contracts')


if __name__ == '__main__':
    main()
