#!/usr/bin/env python3
"""Verify descriptor-specific unused witness-instantiation arguments.

The probe is generic over every legal Output and Failure, not a concrete
specialization. Its complete compiler body passes the input metatype unchanged
and an undef third operand to swift_getWitnessTable. This is independent of the
external-data catalog and grants no purity, layout or frame effects.
"""
import argparse
import json
from pathlib import Path
import re
import tempfile

try:
    from .generate_darwin_declarations import export_index
    from .generate_swift_data_declarations import _normalized_body, run
    from .generate_swift_metadata_declarations import TARGETS, EXPORT_TARGETS
except ImportError:
    from generate_darwin_declarations import export_index
    from generate_swift_data_declarations import _normalized_body, run
    from generate_swift_metadata_declarations import TARGETS, EXPORT_TARGETS

SOURCE = '''import Combine
@_silgen_name("neverd_publisher_probe")
func observe<P: Publisher>(_ type: P.Type)
@_silgen_name("neverd_generic_publisher_probe")
public func generic<Output, Failure: Error>(_ type: CurrentValueSubject<Output, Failure>.Type) {
  observe(type)
}
'''


def unused_instantiation_argument(ir):
    if len(ir) > 1024 * 1024:
        raise ValueError('witness contract IR exceeds its input budget')
    functions = re.findall(
        r'^define swiftcc void @neverd_generic_publisher_probe\(ptr '
        r'(%[A-Za-z_0-9.]+)\)(?: #[0-9]+)? \{\n(.*?)^\}',
        ir, re.M | re.S)
    headers = re.findall(r'^define [^\n]*@neverd_generic_publisher_probe[^\n]*$', ir, re.M)
    if len(functions) != 1 or len(headers) != 1:
        raise ValueError('missing or ambiguous generic metatype probe')
    for name, declaration in (
            ('swift_getWitnessTable', 'ptr @swift_getWitnessTable(ptr, ptr, ptr)'),
            ('neverd_publisher_probe', 'swiftcc void @neverd_publisher_probe(ptr, ptr, ptr)')):
        declarations = re.findall(r'^declare ([^\n]*@' + name + r'[^\n]*)$', ir, re.M)
        if len(declarations) != 1 or not re.fullmatch(
                re.escape(declaration) + r'(?: local_unnamed_addr)?(?: #[0-9]+)?',
                declarations[0]):
            raise ValueError('unexpected witness/protocol call ABI')
    parameter, body = functions[0]
    descriptors = re.findall(
        r'@swift_getWitnessTable\(ptr nonnull @"([^"\n]+)"', body)
    if len(descriptors) != 1:
        raise ValueError('missing unique descriptor input')
    descriptor = descriptors[0]
    declarations = re.findall(r'^@"' + re.escape(descriptor) + r'" = ([^\n]+)$', ir, re.M)
    if declarations != ['external global %swift.protocol_conformance_descriptor, align 4']:
        raise ValueError('descriptor is not exact direct external storage')
    expected = '''entry:
 %witness = tail call ptr @swift_getWitnessTable(ptr nonnull @"DESCRIPTOR", ptr %type, ptr undef)
 tail call swiftcc void @neverd_publisher_probe(ptr %type, ptr %type, ptr %witness)
 ret void
'''.replace('DESCRIPTOR', descriptor)
    if _normalized_body(body, parameter) != _normalized_body(expected, '%type'):
        raise ValueError('generic witness flow or unused argument is not proved')
    return descriptor


def render(profiles, exports, version, compiler):
    if len(profiles) != 4 or len(exports) != 4 or len(set(profiles)) != 1:
        raise ValueError('all four generic compiler profiles must agree')
    name = profiles[0]
    modules = [exports[i].get(name, set()) & exports[i + 1].get(name, set())
               for i in (0, 2)]
    if not all(modules):
        raise ValueError('descriptor must be exported in all four SDK profiles')
    return '\n'.join([
        '// clang-format off',
        '// Generated by scripts/generate_swift_witness_contracts.py.',
        f'// Generic metatype proof: MacOSX SDK {version}.',
        '// ' + compiler.replace('\n', '; '),
        '// Target profiles: ' + ', '.join(TARGETS),
        '// Only swift_getWitnessTable argument 2 is unused for this conformance.',
        '// No descriptor layout, purity, frame borrowing or value-witness ABI.',
        '{' + ', '.join(json.dumps(x) for x in
                       (name, *('|'.join(sorted(m)) for m in modules))) + '},',
        '// clang-format on', ''])


def main():
    import yaml
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sdk', type=Path, required=True)
    parser.add_argument('--swiftc', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    sdk = args.sdk.resolve(strict=True)
    with tempfile.TemporaryDirectory(prefix='neverd-witness-contract-') as work:
        source = Path(work) / 'probe.swift'
        source.write_text(SOURCE)
        profiles = []
        for index, target in enumerate(TARGETS):
            ir = Path(work) / f'{index}.ll'
            run([str(args.swiftc), '-O', '-parse-as-library', '-target', target,
                 '-sdk', str(sdk), '-emit-ir', str(source), '-o', str(ir)])
            profiles.append(unused_instantiation_argument(ir.read_text()))
    class TBDLoader(yaml.SafeLoader):
        pass
    TBDLoader.add_constructor('!tapi-tbd', lambda loader, node:
                              loader.construct_mapping(node, deep=True))
    path = sdk / 'System/Library/Frameworks/Combine.framework/Versions/A/Combine.tbd'
    documents = list(yaml.load_all(path.read_text(), Loader=TBDLoader))
    exports = [export_index(documents, target) for target in EXPORT_TARGETS]
    output = render(profiles, exports,
                    json.loads((sdk / 'SDKSettings.json').read_text())['Version'],
                    run([str(args.swiftc), '--version']).strip())
    if args.check:
        if args.output.read_text() != output:
            parser.error('generated witness contracts differ')
    else:
        args.output.write_text(output)
    print('verified one descriptor-specific generic witness contract')


if __name__ == '__main__':
    main()
