#!/usr/bin/env python3
"""Extract common external, non-TLS data declarations and SDK export facts.

The generated catalog records linker identities, not object contents or SDK
implementations. Generation requires libclang and PyYAML; consumers do not.
"""
import argparse
import ctypes
import json
from pathlib import Path
import tempfile

try:
    from .generate_darwin_declarations import CDeclarations, load_exports
    from .generate_objc_declarations import CXCursor, TARGETS, catalog_rows
except ImportError:
    from generate_darwin_declarations import CDeclarations, load_exports
    from generate_objc_declarations import CXCursor, TARGETS, catalog_rows


class DataDeclarations(CDeclarations):
    def __init__(self, library):
        super().__init__(library)
        self.bind("clang_getCursorTLSKind", ctypes.c_uint, CXCursor)

    def declaration(self, cursor):
        if cursor.kind != 9 or self.clang_getCursorLinkage(cursor) != 4:
            return None
        name = self.string(self.clang_Cursor_getMangling(cursor))
        if not name.startswith("_"):
            return None
        # A TLS symbol requires thread-specific access and cannot use an
        # ordinary external storage address. Keep its negative evidence.
        return name[1:], "data" if self.clang_getCursorTLSKind(cursor) == 0 else ""


def render(profiles, exports, version, compiler):
    lines = ["// clang-format off",
             "// Generated by scripts/generate_darwin_data_declarations.py.",
             f"// Compiler-derived external data/export facts: MacOSX SDK {version}.",
             f"// {compiler}", "// Target profiles: " + ", ".join(TARGETS),
             "// No SDK implementation or object contents are included."]
    count = 0
    for name, arm, intel in catalog_rows(profiles):
        if not any(name in index for index in exports):
            continue
        modules = ["|".join(sorted(index.get(name, ()))) if kind == "data" else ""
                   for kind, index in zip((arm, intel), exports)]
        lines.append("{" + ", ".join(json.dumps(x) for x in (name, *modules)) + "},")
        count += 1
    lines.append("    // clang-format on")
    return "\n".join(lines) + "\n", count


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sdk", type=Path, required=True)
    parser.add_argument("--libclang", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sdk = args.sdk.resolve(strict=True)
    clang = DataDeclarations(args.libclang)
    with tempfile.TemporaryDirectory(prefix="neverd-darwin-data-") as work:
        source = Path(work) / "declarations.m"
        source.write_text(
            "#import <Foundation/Foundation.h>\n#include <objc/runtime.h>\n"
            "#include <objc/objc-sync.h>\n#include <pthread.h>\n"
            "#include <dispatch/dispatch.h>\n")
        profiles = [clang.extract(source, sdk, target) for target in TARGETS]
    version = json.loads((sdk / "SDKSettings.json").read_text())["Version"]
    output, count = render(profiles, load_exports(sdk), version,
                           clang.string(clang.clang_getClangVersion()))
    if args.check:
        if args.output.read_text() != output:
            parser.error("generated data catalog differs; regenerate with this SDK")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(mode="w", dir=args.output.parent,
                                         delete=False) as temporary:
            temporary.write(output)
            staging = Path(temporary.name)
        try:
            staging.replace(args.output)
        finally:
            staging.unlink(missing_ok=True)
    print(f"verified {count} external data declaration rows with export evidence")


if __name__ == "__main__":
    main()
