#!/usr/bin/env python3
"""Extract bounded public CoreGraphics record data declarations, not values.

Each architecture requires identical type, size and alignment facts from the
macOS and iOS preprocessing profiles, together with exact SDK export evidence.
"""
import argparse
import ctypes
import json
from pathlib import Path
import tempfile

try:
    from .generate_darwin_data_declarations import DataDeclarations
    from .generate_darwin_declarations import CXType, load_exports
    from .generate_objc_declarations import TARGETS, catalog_rows
except ImportError:
    from generate_darwin_data_declarations import DataDeclarations
    from generate_darwin_declarations import CXType, load_exports
    from generate_objc_declarations import TARGETS, catalog_rows


RECORDS = ("CGAffineTransformIdentity", "CGSizeZero")


class RecordDeclarations(DataDeclarations):
    def __init__(self, library):
        super().__init__(library)
        self.bind("clang_Type_getSizeOf", ctypes.c_longlong, CXType)
        self.bind("clang_Type_getAlignOf", ctypes.c_longlong, CXType)

    def declaration(self, cursor):
        storage = super().declaration(cursor)
        if not storage or storage[0] not in RECORDS:
            return None
        if storage[1] != "data":
            return storage[0], ""
        value = self.clang_getCursorType(cursor)
        canonical = self.clang_getCanonicalType(value)
        encoding = self.string(self.clang_getDeclObjCTypeEncoding(cursor))
        size = self.clang_Type_getSizeOf(value)
        alignment = self.clang_Type_getAlignOf(value)
        if canonical.kind != 105 or not encoding.startswith("{") or \
                not 0 < size <= 65535 or not 0 < alignment <= size:
            return storage[0], ""
        return storage[0], json.dumps((encoding, size, alignment))


def common_record(value):
    if not value:
        return None
    try:
        encoding, size, alignment = json.loads(value)
    except (ValueError, TypeError):
        return None
    if not isinstance(encoding, str) or not encoding.startswith("{") or \
            type(size) is not int or type(alignment) is not int or \
            not 0 < size <= 65535 or not 0 < alignment <= size or \
            alignment & (alignment - 1):
        return None
    return encoding, size, alignment


def render(profiles, exports, version, compiler):
    lines = ["// clang-format off",
             "// Generated by scripts/generate_darwin_record_data_declarations.py.",
             f"// Compiler-derived external record types: MacOSX SDK {version}.",
             f"// {compiler}", "// Target profiles: " + ", ".join(TARGETS),
             "// No object contents, initialization or call effects are included."]
    rows = list(catalog_rows(profiles))
    # An alternative declaration supplies no unique record layout.
    counts = {name: sum(row[0] == name for row in rows) for name, _, _ in rows}
    count = 0
    for name, arm, intel in rows:
        if name not in RECORDS or counts[name] != 1:
            continue
        facts = [common_record(value) if name in index else None
                 for value, index in zip((arm, intel), exports)]
        if not any(facts):
            continue
        values = [name]
        for fact, index in zip(facts, exports):
            values.extend((*fact, "|".join(sorted(index[name]))) if fact
                          else (None, 0, 0, ""))
        lines.append("{" + ", ".join("nullptr" if value is None else
                                     json.dumps(value) for value in values) + "},")
        count += 1
    lines.append("    // clang-format on")
    return "\n".join(lines) + "\n", count


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sdk", type=Path, required=True)
    parser.add_argument("--libclang", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sdk = args.sdk.resolve(strict=True)
    clang = RecordDeclarations(args.libclang)
    with tempfile.TemporaryDirectory(prefix="neverd-darwin-record-data-") as work:
        source = Path(work) / "declarations.m"
        source.write_text("#import <CoreGraphics/CoreGraphics.h>\n")
        profiles = [clang.extract(source, sdk, target) for target in TARGETS]
    version = json.loads((sdk / "SDKSettings.json").read_text())["Version"]
    output, count = render(profiles, load_exports(sdk, ("CoreGraphics",)), version,
                           clang.string(clang.clang_getClangVersion()))
    if args.check:
        if args.output.read_text() != output:
            parser.error("generated record data catalog differs; regenerate with this SDK")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(mode="w", dir=args.output.parent,
                                         delete=False) as temporary:
            temporary.write(output)
            staging = Path(temporary.name)
        try:
            staging.replace(args.output)
        finally:
            staging.unlink(missing_ok=True)
    print(f"verified {count} common record data rows with export evidence")


if __name__ == "__main__":
    main()
